### ISSUE TITLE
AspNetIdentity sample has inconsistent Startup code

### ISSUE THREAD

**Issue by cb55555** [thinktecture/Thinktecture.IdentityServer.v3.Samples#35]
In the configuration method of the OWIN Startup class, most of the sample projects are modelled like this:

```c#
            app.Map("/core", coreApp =>
            {
                ...
                var options = new IdentityServerOptions
                {
                    IssuerUri = "https://idsrv3.com",
                    SiteName = "Thinktecture IdentityServer v3 - CustomUserService",
                    ...
                };

                coreApp.UseIdentityServer(options);
            });
```
However, in the AspNetIdentity sample project, the code looks like this.

```c#
            appBuilder.Map("/admin", adminApp =>
            {
                ...
            });

            var options = new IdentityServerOptions
            {
                IssuerUri = "https://idsrv3.com",
                SiteName = "Thinktecture IdentityServer v3 - UserService-AspNetIdentity",
                ...                }
            };

            appBuilder.UseIdentityServer(options);
```

First, the mapping is being set for the "/admin" path, whereas it's being set for "/core" in the other samples.

Second, the call to UseIdentityServer() is called outside of the anonymous method, whereas it's called inside the anonymous method in the other samples.

**Comment by cb55555** [comment]
Is there a reason for this difference?

**Comment by brockallen** [comment]
Notice what's in the map -- there is a difference.

**Comment by cb55555** [comment]
Yes, I know that the AspNetIdentity sample creates a factory for IdentityManager and maps for it, but doesn't it still need to map for IdentityServer as well?

**Comment by brockallen** [comment]
Not necessarily. In this sample, IIRC, the `/core` is from the hosting URL, not from an OWIN map.
