### ISSUE TITLE
Configure Thinktecture Identity Server v3 for production use

### ISSUE THREAD

**Issue by sandeepgaikwad** [thinktecture/Thinktecture.IdentityServer.v3.Samples#51]
Hello,
I have been evaluating Thinktecture Identity server v3 for authentication and authorization.
I am at a point where I have setup v3 locally and also build small MVC web apps to get authenticated/ authorized from Thinktecture identity server v3 (thanks to all the samples).

Thinktecture v3 sets in-memory clients/user/claims. 
Now I want to use Thinktecture Identity server v3 in production scenario, where I want to setup a database from which I can load users/ claims/roles.
I have read about Identity manager, MembershipReboot, but could not figure out how to use it (too many entities). 
Also I need to understand what is the use of Thinktecture.Identitymanager.MembershipReboot; as per its description, I think this is what I need, but what about the UI? How can I setup users/roles, etc. Do I need deploy Identitymanager separately for this?

The videos at vimeo at related to older v3 version, so it adds to the confusion.
Not sure how to move ahead, I know I am few steps away from achieving the goal.

Kindly provide some help as to how can I setup everything in a production environment.

Thanks
Sandeep

**Comment by leastprivilege** [comment]
Wrong repo for that question.

We realize that the docs are not fully synced with the code right now - we are working on it, and things will become better by RTM time (end of jan). The samples should have most of what you need though.
