### ISSUE TITLE
Any Samples to Optionally Include Domain Credentials if the Realm Is Domain Without AD FS 

### ISSUE THREAD

**Issue by kirkpabk** [thinktecture/Thinktecture.IdentityServer.v3.Samples#54]
I've been looking for a scaled down solution, possibly something that could be added to the IdentityServer OWIN pipeline like Use.CustomDomainCredentialProvider to provide an optional assertion for Domain Credentials to be used when accessing network resources.

Did I miss an example in the existing samples?  In v1 or v2, there were some posts but nothing formal, is there something similar for v3.  It just seems this relatively common scenario is sort of hit and miss across open source identity management.  Thanks in advance.

**Comment by brockallen** [comment]
Do you mean for user authentication?

**Comment by kirkpabk** [comment]
Yes, need to make sure that a challenge is made if the user is on the domain to pick up the account, match it with a registered account. {e.g. Custom account or Google} while being able to go to another server within a subdomain and use domain resources {with or without kerberos} .  Does that make sense?

**Comment by brockallen** [comment]
Yes, it makes sense, but I think I'm missing the whole story. That's ok - the short answer is that we have the PreAuthenticate hook in the user service to allow for host-based authN scenarios (like windows authN). I have a TODO to build a sample for this, but haven't had time as of yet.
