### ISSUE TITLE
Need a little guidance

### ISSUE THREAD

**Issue by vigsgb** [thinktecture/Thinktecture.IdentityServer.v3.Samples#56]
I am going over the examples provided and am a bit confused on how I could achieve the following:

1. Authenticate user with windows authentication
2. After authentication I want to take the user name and verify that against a custom database then apply the proper claims based on the security in that database.
3. Have the ability for a user to sign off then enter credentials.  Basically switch users.

What I need is just a little shove in the right direction....  such as flow and where I would perform those tasks.    Not looking for a complete solution just a little direction.

Thanks Much
Greg

**Comment by brockallen** [comment]
1) We don't have a sample for windows authentication, but the PreAuthenticate method on the user service will be involved.
2) The user service is what allows you to map from your user DB to the claims identityserver issues. Check the docs:  https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/advanced/userService.html
3) This are the "Logout" and "Login With a Different Account" links in the UI.

**Comment by vigsgb** [comment]
I totally missed the documentation on the IUserService interface and Factory information.    This along with the other tidbits of information is what I needed.

Thanks for the quick reply and all the work you are doing on this project.
