### ISSUE TITLE
WepApi sample is not working?

### ISSUE THREAD

**Issue by henninga** [thinktecture/Thinktecture.IdentityServer.v3.Samples#57]
Hei

After finally getting all the mvc samples up and running, I'm stuck on getting the WebApi sample working. Is anybody else having the same trouble? If not, is there anything I should be doing?

What I'm doing is starting up the api server and navigating to http://localhost:2727/Identity but all it gives me is {"Message":"Authorization has been denied for this request."}

**Comment by brockallen** [comment]
That's the correct behavior. 1) You did not send a token to authenticate, and 2) Using the browser is not the typical use case (APIs are programmatic, not interactive).
