### ISSUE TITLE
Sample AspNetIdentity is broken.

### ISSUE THREAD

**Issue by gwinnem** [thinktecture/Thinktecture.IdentityServer.v3.Samples#64]
Due to changes in the IdentityManager, the sample is not working.
So if you like me want the latest nuget releases you will run into trouble in line 18 in Startup.cs.
IdentityManager is not having the IdentityManagerConfiguration class anymore. And the signature for the extension class having the UseIdentityManager requires IdentityManagerOptions as the new parameter.

Fileref:https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/blob/master/source/AspNetIdentity/SelfHost/Startup.cs

**Comment by brockallen** [comment]
Well, the sample is working as-is. I think you mean that if you update the IdMgr NuGet, then it's no longer working.

The sample on the dev branch is already updated. Once we do RTM then we'll merge all dev samples to master.

**Comment by gwinnem** [comment]
Tnxs for the quick reply, and for the awesome work you guys are doing.
Totally correct that i updated the IdMgr Nuget, but i mentioned that in 
the issue.
Ill wait until the RTM before i say anything more :)


Best Regards
Geirr
On 18/01/2015 15:32, Brock Allen wrote:
>
> Well, the sample is working as-is. I think you mean that if you update 
> the IdMgr NuGet, then it's no longer working.
>
> The sample on the dev branch is already updated. Once we do RTM then 
> we'll merge all dev samples to master.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/issues/64#issuecomment-70410300>.
>

-- 
Best Regards

Geirr Winnem
